version: '3.1'
services:
    drugindicationapi:
        build:
            context: .
        container_name: drugindicationapi
        restart: always
        ports:
            - 5000:8080
        depends_on:
            - mongo
        env_file:
            - .env
        networks:
            - drugindicationnet

    mongo:
        image: mongo:6.0
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
            - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - drugindicationnet

volumes:
  mongo_data:

networks:
    drugindicationnet:
        driver: bridge
