name: Docker environment Automation

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Project restore
        run: dotnet restore src/DrugIndication.API/DrugIndication.Api.csproj

      - name: Unit tests
        run: dotnet test tests/DrugIndication.UnitTests/DrugIndication.UnitTests.csproj

      - name: DockerHub Authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Building and pushing docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/drugindicationapi:latest
